// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from '@prisma/config';

export default defineConfig({
  datasource: {
    url: process.env.DATABASE_URL!,
  },
  // On ajoute explicitement l'engine pour satisfaire le type strict de Prisma
  engine: {
    type: 'library' // ou 'binary' selon ta config, mais 'library' est le standard actuel
  }
});